#!/usr/bin/env bash

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua/bian/lsp

for f in `find * -regex ".*\.lua$"`; do
	echo $f
	rm -rf ~/.config/nvim/$f
	ln -s ~/dotfiles/$f ~/.config/nvim/$f
done
